---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "create ~/web"
  ansible.builtin.file:
    path: ~/web
    state: directory
    mode: '0755'

- name: "copy files"
  copy:
    src: index.js
    dest: ~/web
    backup: true

- name: "start server"
  shell: pm2 start ~/web/index.js -f